import datetime

class ReportGenerator:
    """Generates structured digital HTML reports and printable templates for OA screening."""

    @staticmethod
    def generate_html_report(patient: dict, screening: dict, prediction: dict) -> str:
        features = prediction.get("features", {})
        importances = prediction.get("feature_importance", {})

        importance_items = "".join(
            f"<li><strong>{k.replace('_', ' ').title()}:</strong> (Importance Impact: {v:.2f})</li>"
            for k, v in importances.items()
        )

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8" />
            <title>OA-SMART Screening Report</title>
            <style>
                body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 40px; color: #1e293b; background: #fff; }}
                .header {{ border-bottom: 2px solid #0284c7; padding-bottom: 15px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }}
                .title {{ color: #0369a1; margin: 0; font-size: 24px; font-weight: 700; }}
                .badge {{ background: #e0f2fe; color: #0369a1; padding: 6px 12px; borderRadius: 20px; font-weight: bold; }}
                .section {{ margin-bottom: 25px; }}
                .section-title {{ font-size: 16px; font-weight: 700; color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 10px; }}
                .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }}
                .card {{ background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; }}
                .result-box {{ background: #f0fdf4; border: 1px solid #bbf7d0; padding: 20px; border-radius: 8px; font-size: 18px; color: #166534; margin-top: 15px; }}
                .disclaimer {{ font-size: 11px; color: #64748b; margin-top: 40px; border-top: 1px solid #cbd5e1; padding-top: 10px; }}
            </style>
        </head>
        <body>
            <div class="header">
                <div>
                    <h1 class="title">OA-SMART Clinical Screening Report</h1>
                    <small>Portable AI-Assisted Osteoarthritis Screening System</small>
                </div>
                <div class="badge">Screening ID: {screening.get('id', 'N/A')}</div>
            </div>

            <div class="grid">
                <div class="card">
                    <div class="section-title">Patient Profile</div>
                    <p><strong>Name:</strong> {patient.get('name', 'N/A')}</p>
                    <p><strong>Patient ID:</strong> {patient.get('id', 'N/A')}</p>
                    <p><strong>Age / Gender:</strong> {patient.get('age', 'N/A')} / {patient.get('gender', 'N/A')}</p>
                </div>
                <div class="card">
                    <div class="section-title">Session Details</div>
                    <p><strong>Date & Time:</strong> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
                    <p><strong>Test Executed:</strong> {screening.get('test_type', 'SIT_TO_STAND')}</p>
                    <p><strong>Model Version:</strong> {prediction.get('model_version', 'RF-1.0.0')}</p>
                </div>
            </div>

            <div class="result-box">
                <strong>Overall Screening Result:</strong> {prediction.get('prediction', 'UNEVALUATED')}<br/>
                <span style="font-size: 14px; color: #334155; display: inline-block; margin-top: 5px;">
                    {prediction.get('recommendation', 'Consult clinical health professional.')}
                </span>
            </div>

            <div class="section" style="margin-top: 25px;">
                <div class="section-title">Key Movement Indicators & Feature Importances</div>
                <ul>
                    {importance_items}
                </ul>
            </div>

            <div class="section">
                <div class="section-title">Extracted Sensor Biometrics</div>
                <p><strong>Knee Angle Range:</strong> {features.get('knee_angle_range', 0.0):.1f}°</p>
                <p><strong>Mean Knee Angle:</strong> {features.get('knee_angle_mean', 0.0):.1f}°</p>
                <p><strong>Thigh Acceleration RMS:</strong> {features.get('thigh_acc_rms', 0.0):.3f} g</p>
                <p><strong>Lower Leg Acceleration RMS:</strong> {features.get('lower_leg_acc_rms', 0.0):.3f} g</p>
            </div>

            <div class="disclaimer">
                <strong>CLINICAL DISCLAIMER:</strong> This report is generated by the OA-SMART AI screening assistant for risk stratification only. It does NOT constitute a definitive medical diagnosis. Clinical evaluation should be performed by a qualified healthcare professional.
            </div>
        </body>
        </html>
        """
        return html
